import fs from "node:fs";
import path from "node:path";
import type { Config } from "drizzle-kit";

/**
 * Resolves the local D1 SQLite database path from wrangler's miniflare state directory.
 *
 * Scans `.wrangler/state/v3/d1/miniflare-D1DatabaseObject` for `.sqlite` files.
 * Falls back to a predictable default if the directory or files are absent.
 */
function getLocalD1Path(): string {
  const d1Dir = ".wrangler/state/v3/d1/miniflare-D1DatabaseObject";
  if (fs.existsSync(d1Dir)) {
    const files = fs.readdirSync(d1Dir).filter((f) => f.endsWith(".sqlite"));
    if (files.length > 0) {
      return path.join(d1Dir, files[0]);
    }
  }
  // Fallback - will error if not found, but that's expected if no local DB exists
  return ".wrangler/state/v3/d1/miniflare-D1DatabaseObject/local.sqlite";
}

/**
 * Drizzle Kit configuration for local D1 (SQLite) development.
 *
 * Uses the local miniflare SQLite file generated by `wrangler dev` so that
 * `drizzle-kit generate` and `drizzle-kit migrate` target the same database
 * the local Worker sees.
 */
export default {
  schema: "./lib/db/schema.ts",
  out: "./migrations",
  dialect: "sqlite",
  dbCredentials: {
    url: getLocalD1Path(),
  },
} satisfies Config;
